#!/usr/bin/env python3
"""Regenerate notes/index.md from the pages on disk plus the classification map.

Hand-maintaining the index across ~50 page writes goes stale immediately, so it
is generated: domain order and page summaries come from the pages themselves,
the bookkeeping sections from the map and from what has actually been written.

Usage:  python scripts/build_index.py
"""
import csv
import io
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "notes"
MAP = ROOT / "processed" / "Zotero_library_map.csv"

DOMAIN_ORDER = [
    ("photovoltaics", "Photovoltaics", "Photovoltaics"),
    ("solar-park-development", "Solar park development", "Solar_Park_Development"),
    ("agrivoltaics", "Agrivoltaics", "Agrivoltaics_and_Dual_Use"),
    ("energy-systems", "Energy systems", "Energy_Systems"),
    ("plant-photobiology", "Plant photobiology", "Plant_Photobiology"),
    ("controlled-environment-agriculture", "Controlled environment agriculture",
     "Controlled_Environment_Agriculture"),
    ("forestry", "Forestry", "Forestry"),
    ("geospatial", "Geospatial", "Geospatial"),
    ("data-sources", "Data sources", "Data_Sources"),
    ("tools-and-methods", "Tools and methods", "Tools_and_Methods"),
    ("themes", "Themes", "Themes"),
    ("other-topics", "Other topics", "Other_Topics"),
]

SPLIT_THRESHOLD = 80
BULLET = re.compile(r"^- ", re.M)
CANDIDATE = re.compile(r"^##\s+Candidate:\s*(.+?)\s*$", re.M)


def page_info(path):
    text = path.read_text(encoding="utf-8")
    fm = text.split("---", 2)[1] if text.startswith("---") else ""
    dom = ""
    m = re.search(r"domain/([a-z-]+)", fm)
    if m:
        dom = m.group(1)
    is_moc = "moc" in fm
    m = re.search(r"^\*\*Summary\*\*:\s*(.+?)$", text, re.M)
    summary = m.group(1).strip() if m else ""
    body = text.split("## Notes", 1)[1] if "## Notes" in text else ""
    n = len(BULLET.findall(body))
    cands = {}
    for cm in CANDIDATE.finditer(text):
        section = text[cm.end():].split("\n## ", 1)[0]
        cands[cm.group(1)] = len(BULLET.findall(section))
    return dom, is_moc, summary, n, cands


def first_sentence(s, limit=150):
    s = s.strip()
    cut = s.split(". ")[0].rstrip(".")
    if len(cut) > limit:
        cut = cut[:limit].rsplit(" ", 1)[0] + "…"
    return cut


def main():
    rows = list(csv.DictReader(MAP.open(encoding="utf-8-sig")))
    mapped = Counter(r["primary_page"] for r in rows)

    infos = {}
    for path in sorted(NOTES.glob("*.md")):
        if path.stem in ("index", "log"):
            continue
        infos[path.stem] = page_info(path)

    by_domain = defaultdict(list)
    mocs = {}
    for name, (dom, is_moc, summary, n, cands) in infos.items():
        if is_moc:
            mocs[dom] = (name, summary)
        else:
            by_domain[dom].append((name, summary, n))

    out = ["# Index", "",
           "**Summary**: Map of content — every page in the vault with a one-line description, "
           "grouped by domain in the order used by `TAXONOMY.md`.",
           "**Updated**: 2026-08-25", "", "---", "",
           "Generated by `scripts/build_index.py`. Note counts are bullets currently on the page; "
           "pages still to be written by the bulk import show their mapped count in brackets.", ""]

    for dom, label, moc_name in DOMAIN_ORDER:
        out.append("## " + label)
        out.append("")
        if dom in mocs:
            name, summary = mocs[dom]
            out.append("- [[{}]] — MOC: {}".format(name, first_sentence(summary)))
        for name, summary, n in sorted(by_domain.get(dom, [])):
            pending = mapped.get(name, 0) - n
            suffix = "  ({} notes)".format(n) if n else ""
            if pending > 0:
                suffix = "  ({} notes, {} mapped and not yet written)".format(n, pending) if n \
                    else "  [{} mapped, not yet written]".format(pending)
            out.append("- [[{}]] — {}{}".format(name, first_sentence(summary), suffix))
        out.append("")

    out += ["---", "", "## Candidate topics", ""]
    cand_lines = []
    for name, (_, _, _, _, cands) in sorted(infos.items()):
        for cand, n in cands.items():
            mark = "  **at threshold — promote**" if n >= 5 else ""
            cand_lines.append("- {} (on [[{}]]) — {} note{}{}".format(
                cand, name, n, "" if n == 1 else "s", mark))
    for r in rows:
        pass
    unsorted_cands = Counter(r["candidate"] for r in rows if r["candidate"])
    for cand, n in unsorted_cands.items():
        if not any(cand in line for line in cand_lines):
            cand_lines.append("- {} — {} notes (mapped, not yet written)".format(cand, n))
    out += cand_lines or ["None."]
    out.append("")

    out += ["## Proposed splits / merges", ""]
    over = []
    for name, (_, is_moc, _, n, _) in sorted(infos.items()):
        total = max(n, mapped.get(name, 0))
        if not is_moc and total > SPLIT_THRESHOLD:
            over.append("- [[{}]] — {} notes, over the ~{} threshold.".format(
                name, total, SPLIT_THRESHOLD))
    out += over or ["None. The six pages flagged before the import were split; "
                    "see the `TAXONOMY.md` changelog."]
    out.append("")

    out += ["## Proposed domains", "", "None.", ""]

    # count what is actually written on the pages: a #needs-review flag is
    # often on a sub-bullet (a duplicate Zotero record), not in the map tags
    written = []
    for f in sorted(NOTES.glob('*.md')):
        if f.name in ('index.md', 'log.md'):
            continue
        written.append(io.open(str(f), encoding='utf-8').read())
    written = chr(10).join(written)
    needs_review = written.count('#needs-review')
    needs_topic = written.count('#needs-topic')
    written = sum(n for _, (_, is_moc, _, n, _) in infos.items() if not is_moc)
    out += ["## Needs attention", "",
            "- Zotero items mapped: {} · bullets written: {}".format(len(rows), written),
            "- `#needs-review`: {}".format(needs_review),
            "- `#needs-topic`: {}".format(needs_topic),
            ""]

    (NOTES / "index.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote notes/index.md ({} pages, {} bullets)".format(len(infos), written))


if __name__ == "__main__":
    main()
